//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPORTnamespace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contestant
    {
        public decimal ID { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public string Country { get; set; }
        public string SportID { get; set; }
    
        public virtual SPORT SPORT { get; set; }
    }
}
